print('           /^\/^\\')
print('         _|__|  O|')
print('\/     /~     \_/ \\')
print(' \____|__________/ \\')
print('        \_______     \\')
print('                `\     \                 \\')
print('                  |     |                  \\')
print('                 /      /                    \\')
print('                /     /                       \\\\')
print('              /      /                         \ \\')
print('             /     /                            \  \\')
print('           /     /             _----_            \   \\')
print('          /     /           _-~      ~-_         |   |')
print('         (      (        _-~    _--_    ~-_     _/   |')
print('          \      ~-____-~    _-~    ~-_    ~-_-~    /')
print('            ~-_           _-~          ~-_       _-~')
print('               ~--______-~                ~-___-~')

input('press enter to put snake to sleep')